language: go
go: 
 - 1.1
 - 1.2
 - 1.3
 - release
 - tip
before_install:
 - .ci-scripts/before_install.sh
install:
 - .ci-scripts/install.sh
before_script:
 - .ci-scripts/before_script.sh
script:
 - .ci-scripts/script.sh
after_success:
 - .ci-scripts/after_succeess.sh
after_failure:
 - .ci-scripts/after_failure.sh
after_script:
 - .ci-scripts/after_script.sh
